# Generated by Django 3.1.2 on 2021-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consignment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=20)),
                ('item_weight', models.FloatField()),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
