# Generated by Django 3.1.2 on 2021-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20210101_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='item_name',
        ),
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
