# Generated by Django 3.1.2 on 2021-01-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_auto_20210101_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
