# Generated by Django 4.0 on 2022-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='currentAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='userImage',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsContactNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanentAddress',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
