# Generated by Django 4.0 on 2022-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_remove_profile_bio_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('TEACHER', 'teacher'), ('STUDENT', 'student'), ('ACCOUNTANT', 'ACCOUNTANT')], default='student', max_length=20),
        ),
    ]
