# Generated by Django 4.0 on 2022-01-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('TEACHER', 'teacher'), ('STUDENT', 'student'), ('ACCOUNTANT', 'accountant')], default='student', max_length=20),
        ),
    ]
