# Generated by Django 4.0 on 2022-01-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currentAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanentAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
