# Generated by Django 4.0.1 on 2022-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_alter_profile_currentaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fatherName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
