# Generated by Django 4.0.1 on 2022-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0011_profile_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
